[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://visionary-klepon-c89c8c.netlify.app/*"
  to = "https://stellular-palmier-ea7df4.netlify.app/:splat"
  status = 301
  force = true